@dsr_web_api_HostAddress = http://localhost:5254
@apikey = f3dcfyfew298tlhsyu3qwspblor60lht

GET {{dsr_web_api_HostAddress}}/usersinfo
Accept: application/json
x-api-key: {{apikey}}


###
# ===================== GET ALL USERS =====================
GET http://localhost:5254/usersinfo
x-api-key: {{apikey}}
###

# ===================== GET USER BY ID =====================
GET http://localhost:5254/usersinfo/2
x-api-key: {{apikey}}
###

# ===================== CREATE USER (POST) =====================
POST http://localhost:5254/usersinfo
Content-Type: application/json
x-api-key: {{apikey}}

{
    "firtName": "tasnif",
    "lastName": "ansari",
    "email": "tasnif@example.com",
    "mobile": "9876543210",
    "userName": "tasnif",
    "passwordHash": "Pass@123",
    "createdBy": 1,
    "createdOn": "2025-12-10T14:28:02.4127919"
}
###

# ===================== UPDATE USER (PUT) =====================
PUT http://localhost:5254/usersinfo/2
Content-Type: application/json
x-api-key: {{apikey}}

{
    "id": 2,
    "firtName": "Mohammad Mohtashim",
    "lastName": "Ansari",
    "email": "mohtashim535@example.com",
    "mobile": "9075903590",
    "PasswordHash": "admin@123",
    "userName": "admin",
    "isActive": true,
    "lastLoginDateTime": "2025-01-01T10:00:00",
    "updatedBy": 1,
    "updatedOn": "2025-12-10T14:28:02.4127919"
}

###

# ===================== DELETE USER (SOFT DELETE) =====================
DELETE http://localhost:5254/usersinfo/2
x-api-key: {{apikey}}
###
